project:
  type: website

website:
  title: "AI in the Future"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - analysis.qmd
      - Source.qmd 
      - about.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



